#ifndef ROBOTCHEERS_TH03_DEVICH_H__
#define ROBOTCHEERS_TH03_DEVICH_H__

#define ROBOTCHEERS_TH03_MAGIC 'q'
#define ROBOTCHEERS_TH03_IOCRESET _IO(ROBOTCHEERS_TH03_MAGIC, 0)
#define ROBOTCHEERS_TH03_IOCSTATUS _IO(ROBOTCHEERS_TH03_MAGIC, 1)
#define ROBOTCHEERS_TH03_IOCWAKEUP _IO(ROBOTCHEERS_TH03_MAGIC, 2)
#define ROBOTCHEERS_TH03_IOCWAKEUP_ANGLE _IO(ROBOTCHEERS_TH03_MAGIC, 3)

#endif
